import { defineConfig } from 'tsdown'

// Host-only package: bundle the tsc emit. The Typert host/remote artifacts
// (lib/typert.*) are regenerated by scripts/gen-typert.mts in the build
// script before tsc runs.
export default defineConfig({
  entry: ['lib/types/index.js', 'lib/types/invariant.js'],
  outDir: 'lib',
  format: ['esm'],
  platform: 'node',
  target: 'es2024',
  fixedExtension: false,
  dts: false,
  clean: false,
})
