/**
 * Generated by scripts/sync-icon-artwork.mts from @deepseek-ai/dsh-client-ui-primitives
 * (v0.1.7-rc.1, harness 46a7f68b09) — do not edit by hand. The 0.1.5 and rc.1 host lines
 * share no icon export name, so the rc.1 artwork is inlined here: pure SVG,
 * no host runtime identity, identical on every line. Re-run the generator
 * after adding an icon import or bumping the harness checkout.
 *
 * @module @khorsheed/dsh-ui-shortcuts/client
 */

/** Shared props for every product icon component (mirrors the upstream IconProps). */
export interface IconProps {
  /** Square edge in px; defaults to the glyph's own drawn size. */
  size?: number | undefined
  /** Extra class for layout placement; color rides currentColor. */
  className?: string | undefined
}

export const IconChevronDownOutlineMedium = ({ size = 14, className }: IconProps) => (
  <svg width={size} height={size} className={className} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" strokeWidth={1.3}>
    <path d="M4 6L7.29289 9.29289C7.68342 9.68342 8.31658 9.68342 8.70711 9.29289L12 6" stroke="currentColor" />
  </svg>
)
